import { createWithEqualityFn } from "zustand/traditional";
import foto from "./../assets/react.svg";
import freya from "./../assets/freya.jpg";

const useAppStore = createWithEqualityFn((set) => ({
  data: [
    {
      id: 1,
      name: "Romy Saputra Sihananda",
      jenisKelamin: "Laki-laki",
      jurusan: "TKJ",
      tanggalLahir: "2005-12-22",
      agama: "Islam",
      foto,
      katakata:
        "Impian tidak dapat terwujud dengan sendirinya, akan tetapi impian akan datang ketika seseorang berusaha untuk meraihnya",
    },
    {
      id: 2,
      name: "Freyanashifa Jayawardana",
      jenisKelamin: "Perempuan",
      jurusan: "Cheat Foryou",
      tanggalLahir: "2006-02-13",
      agama: "Islam",
      foto: freya,
    },
  ],
  // data: [
  //   {
  //     id: 1,
  //     name: "Romy Saputra Sihananda",
  //     jenisKelamin: "Laki-laki",
  //     jurusan: "TKJ",
  //     tanggalLahir: "2005-12-22",
  //     agama: "Islam",
  //     foto,
  //     katakata:
  //       "Impian tidak dapat terwujud dengan sendirinya, akan tetapi impian akan datang ketika seseorang berusaha untuk meraihnya",
  //   },
  //   {
  //     id: 2,
  //     name: "Freyanashifa Jayawardana",
  //     jenisKelamin: "Perempuan",
  //     jurusan: "Cheat Foryou",
  //     tanggalLahir: "2006-02-13",
  //     agama: "Islam",
  //     foto: freya,
  //   },
  //   {
  //     id: 1,
  //     name: "Romy Saputra Sihananda",
  //     jenisKelamin: "Laki-laki",
  //     jurusan: "TKJ",
  //     tanggalLahir: "2005-12-22",
  //     agama: "Islam",
  //     foto,
  //     katakata:
  //       "Impian tidak dapat terwujud dengan sendirinya, akan tetapi impian akan datang ketika seseorang berusaha untuk meraihnya",
  //   },
  //   {
  //     id: 2,
  //     name: "Freyanashifa Jayawardana",
  //     jenisKelamin: "Perempuan",
  //     jurusan: "Cheat Foryou",
  //     tanggalLahir: "2006-02-13",
  //     agama: "Islam",
  //     foto: freya,
  //   },
  //   {
  //     id: 1,
  //     name: "Romy Saputra Sihananda",
  //     jenisKelamin: "Laki-laki",
  //     jurusan: "TKJ",
  //     tanggalLahir: "2005-12-22",
  //     agama: "Islam",
  //     foto,
  //     katakata:
  //       "Impian tidak dapat terwujud dengan sendirinya, akan tetapi impian akan datang ketika seseorang berusaha untuk meraihnya",
  //   },
  //   {
  //     id: 2,
  //     name: "Freyanashifa Jayawardana",
  //     jenisKelamin: "Perempuan",
  //     jurusan: "Cheat Foryou",
  //     tanggalLahir: "2006-02-13",
  //     agama: "Islam",
  //     foto: freya,
  //   },
  //   {
  //     id: 1,
  //     name: "Romy Saputra Sihananda",
  //     jenisKelamin: "Laki-laki",
  //     jurusan: "TKJ",
  //     tanggalLahir: "2005-12-22",
  //     agama: "Islam",
  //     foto,
  //     katakata:
  //       "Impian tidak dapat terwujud dengan sendirinya, akan tetapi impian akan datang ketika seseorang berusaha untuk meraihnya",
  //   },
  //   {
  //     id: 2,
  //     name: "Freyanashifa Jayawardana",
  //     jenisKelamin: "Perempuan",
  //     jurusan: "Cheat Foryou",
  //     tanggalLahir: "2006-02-13",
  //     agama: "Islam",
  //     foto: freya,
  //   },
  //   {
  //     id: 1,
  //     name: "Romy Saputra Sihananda",
  //     jenisKelamin: "Laki-laki",
  //     jurusan: "TKJ",
  //     tanggalLahir: "2005-12-22",
  //     agama: "Islam",
  //     foto,
  //     katakata:
  //       "Impian tidak dapat terwujud dengan sendirinya, akan tetapi impian akan datang ketika seseorang berusaha untuk meraihnya",
  //   },
  //   {
  //     id: 2,
  //     name: "Freyanashifa Jayawardana",
  //     jenisKelamin: "Perempuan",
  //     jurusan: "Cheat Foryou",
  //     tanggalLahir: "2006-02-13",
  //     agama: "Islam",
  //     foto: freya,
  //   },
  //   {
  //     id: 1,
  //     name: "Romy Saputra Sihananda",
  //     jenisKelamin: "Laki-laki",
  //     jurusan: "TKJ",
  //     tanggalLahir: "2005-12-22",
  //     agama: "Islam",
  //     foto,
  //     katakata:
  //       "Impian tidak dapat terwujud dengan sendirinya, akan tetapi impian akan datang ketika seseorang berusaha untuk meraihnya",
  //   },
  //   {
  //     id: 2,
  //     name: "Freyanashifa Jayawardana",
  //     jenisKelamin: "Perempuan",
  //     jurusan: "Cheat Foryou",
  //     tanggalLahir: "2006-02-13",
  //     agama: "Islam",
  //     foto: freya,
  //   },
  //   {
  //     id: 1,
  //     name: "Romy Saputra Sihananda",
  //     jenisKelamin: "Laki-laki",
  //     jurusan: "TKJ",
  //     tanggalLahir: "2005-12-22",
  //     agama: "Islam",
  //     foto,
  //     katakata:
  //       "Impian tidak dapat terwujud dengan sendirinya, akan tetapi impian akan datang ketika seseorang berusaha untuk meraihnya",
  //   },
  //   {
  //     id: 2,
  //     name: "Freyanashifa Jayawardana",
  //     jenisKelamin: "Perempuan",
  //     jurusan: "Cheat Foryou",
  //     tanggalLahir: "2006-02-13",
  //     agama: "Islam",
  //     foto: freya,
  //   },
  //   {
  //     id: 1,
  //     name: "Romy Saputra Sihananda",
  //     jenisKelamin: "Laki-laki",
  //     jurusan: "TKJ",
  //     tanggalLahir: "2005-12-22",
  //     agama: "Islam",
  //     foto,
  //     katakata:
  //       "Impian tidak dapat terwujud dengan sendirinya, akan tetapi impian akan datang ketika seseorang berusaha untuk meraihnya",
  //   },
  //   {
  //     id: 2,
  //     name: "Freyanashifa Jayawardana",
  //     jenisKelamin: "Perempuan",
  //     jurusan: "Cheat Foryou",
  //     tanggalLahir: "2006-02-13",
  //     agama: "Islam",
  //     foto: freya,
  //   },
  // ],
  addData: (data) => set((state) => ({ data: [...state.data, data] })),
  setData: (data) => set(() => ({ data })),
}));

export default useAppStore;
